export const properties = [
    {
      id: 1,
      title: "Luxury Villa",
      location: "Los Angeles",
      price: 1200000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 2,
      bathrooms: 4,
      parking: 1,
      garages:0,
      type: "Villa",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 2,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 2,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 2,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 2,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 2,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 2,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 2,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 2,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 2,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 2,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },

{
      id: 2,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    // Add more properties...

  ];
  