export const properties = [
    {
      id: 1,
      slug: "luxury-villa",
      title: "Luxury Villa",
      location: "Los Angeles",
      price: 1200000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 2,
      bathrooms: 4,
      parking: 1,
      garages:0,
      type: "Villa",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 2,
      slug: "city-apartment",
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 3,
      slug: "abuja-house",
      title: "Abuja house",
      location: "Lagos, Nigeria",
      price: 50000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 3,
      bathrooms: 2,
      parking: 2,
      garages: 0,
      type: "villa",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 4,
      slug: "asaba-golden-garden",
      title: "Asaba Golden garden",
      location: "Delta, Nigeria",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Rental",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 5,
      slug: "paint-house",
      title: "Paint House",
      location: "Abia",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Accomodation",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 6,
      slug: "12-archars-of-land",
      title: "12 Archars of land",
      location: "Mowe Ibafo",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Lands",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 7,
      slug: "20-unit-rooms-for-rent",
      title: "20 unit rooms for rent",
      location: "Ajao Estate",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Rooms",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 8,
      slug: "city-apartment",
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 9,
      slug: "city-apartment",
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 10,
      slug: "city-apartment",
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 11,
      slug: "city-apartment",
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },

{
      id: 12,
      slug: "city-apartment",
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    // Add more properties...

  ];
  