export const properties = [
    {
      id: 1,
      title: "Luxury Villa",
      location: "Los Angeles",
      price: 1200000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 2,
      bathrooms: 4,
      parking: 1,
      garages:0,
      type: "Villa",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 2,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 3,
      title: "Abuja house",
      location: "Lagos, Nigeria",
      price: 50000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 3,
      bathrooms: 2,
      parking: 2,
      garages: 0,
      type: "villa",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 4,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 5,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 6,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 7,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 8,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 9,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 10,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 11,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },

{
      id: 12,
      title: "City Apartment",
      location: "New York",
      price: 850000,
      image: ["/gow1.png","/gow2.png","/gow3.png","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    // Add more properties...

  ];
  