// "use client"
// import { useState } from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
// import { properties } from "@/constant/data";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const handleSearch = (query: string) => {
  //   // TODO: Implement search functionality
  //   console.log(`Searching for: ${query}`);
  //   setQuery(query);
  // }

  // const [filteredProperties, setFilteredProperties] = useState(properties);

  // const handleSearch = (query: string) => {
  //   const lowerQuery = query.toLowerCase();
  //   const results = properties.filter(
  //     (property) =>
  //       property.title.toLowerCase().includes(lowerQuery) ||
  //       property.location.toLowerCase().includes(lowerQuery) ||
  //       property.price.toString().includes(lowerQuery)
  //   );
  //   setFilteredProperties(results);
  // };

  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
